# Generated by Django 3.2.7 on 2021-09-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='purpose',
            field=models.CharField(default='test', help_text='token purpose', max_length=255),
            preserve_default=False,
        ),
    ]
