# Generated by Django 3.2.7 on 2021-09-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_apitoken_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='apitoken',
            name='allowed_databases',
            field=models.ManyToManyField(to='authentication.SupportedDatabase'),
        ),
    ]
