# Generated by Django 3.2.7 on 2021-10-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20211001_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='owner',
            field=models.CharField(default='t', max_length=255),
            preserve_default=False,
        ),
    ]
