# Generated by Django 3.2.7 on 2021-10-02 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_apitoken_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apitoken',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
