# Generated by Django 3.2.7 on 2021-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20211002_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
